emulator:
  url: "http://127.0.0.1:8000"
  timeout: 10
  auth:
    username: "admin"
    password: "secret_password"

storage:
  specification_path: "data/Swordfish_Specification_v11.2.9.pdf"
  output_path: "reports/"

validator:
  resources_filter: []
