emulator:
  url: "http://127.0.0.1:8080"
  timeout: 10
  auth:
    username: "admin"
    password: "admin"

storage:
  specification_path: "data/Swordfish_v1.2.9_Schema/json-schema/"
  output_path: "reports/"

validator:
  resources_filter: []
